import { useState } from "react";
import {
  ActivityIndicator,
  Button,
  Image,
  Modal,
  ScrollView,
  StatusBar,
  Text,
  View,
  FlatList
} from "react-native";


const students = [
  { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
    { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
    { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
    { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
    { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
    { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
    { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
    { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
    { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
    { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
    { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
    { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
    { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
    { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
   { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
    { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
   { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
    { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
   { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
    { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
   { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
    { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
  { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
    { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
    { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
    { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
    { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
    { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
    { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
    { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
    { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
    { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
    { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
    { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
    { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
    { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
   { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
    { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
   { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
    { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
   { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
    { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
   { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
    { name: "fouad", age: 27 },
  { name: "ibrahim", age: 23 },
  { name: "younes", age: "22" },
];
export default function index() {
 
  return (
   
   <FlatList data={students} renderItem={({item,index})=>{
    console.log(index);
    return (
   <View key={index}>
    <Text>{item.name}</Text>
    <Text>{item.age}</Text>
    </View>
   )}}/>
  );
}
